### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by volkanunsal** [utgarda/sidekiq-status#107]
Hi, I just started using this gem. The first thing I noticed is that the UI doesn't show the Job ids, but instead shows the worker names. 

![screen shot 2017-11-16 at 9 23 38 am](https://user-images.githubusercontent.com/151600/32896255-86b4b514-cab0-11e7-838f-006e7cd64d61.png)

Some of these are auto generated for me, and not really helpful. I have two requests:

- ~~Is it possible to make the job id visible in the row?~~
- Is it possible to allow me to change the display name of my worker?

Thanks.

Edit: I just noticed the job_id is squashed into the arguments column. So never mind that request. :)

**Comment by kenaniah** [comment]
@volkanunsal Looks like you're using the old `0.6.0` version of the gem. If you upgrade to `0.7.0`, the actual class name of your job should display. Also, the `job_id` that you are looking for may be ActiveJob's `provider_job_id` (which is different than the `job_id` in this context). Either way, you can find the it by hovering over the job name. 

Please upgrade to `0.7.0`, which should solve these issues. Thanks!

**Comment by volkanunsal** [comment]
@kenaniah Thanks. I upgraded but still see the `JobWrapper` in that column, but I can click on it now, so that works for me.

**Comment by volkanunsal** [comment]
@kenaniah It's possible they were coming from the cache because I don't see them anymore.
